// Tabela central rota → pageKey (portada do App.tsx do site antigo).
// Usada pelas páginas, pelo sitemap e pela geração de rotas de cidade.
export const PAGE_ROUTES: Record<string, string> = {
  "/": "home",
  "/services/driveways": "drivewayshub_page",
  "/services/driveways/driveways-concrete": "driveways_page",
  "/services/driveways/driveways-paver": "paverdriveways_page",
  "/services/patios": "patioshub_page",
  "/services/patios/patios-concrete": "patios_page",
  "/services/patios/patios-paver": "paverpatios_page",
  "/services/slabs": "slabs_page",
  "/services/porches": "porches_page",
  "/services/sidewalks": "sidewalks_page",
  "/services/footers": "footers_page",
  "/services/sports-courts": "sportscourts_page",
  "/services/steps": "steps_page",
  "/services/garage-floors": "garagefloors_page",
  "/services/curbs-gutters": "curbsgutters_page",
  "/services/approaches": "approaches_page",
  "/services/basement-floors": "basementfloors_page",
  "/services/fire-pits": "firepits_page",
  "/services/seating-walls": "seatingwalls_page",
  "/services/retaining-walls": "retainingwalls_page",
  "/services/fireplaces": "fireplaces_page",
  "/services/outdoor-living": "outdoorliving_page",
  "/services/outdoor-lighting": "outdoorlighting_page",
  "/services/outdoor-kitchens": "outdoorkitchens_page",
  "/services/shelters": "shelters_page",
  "/services/pool-decks-surrounds": "pool_decks_page",
  "/gallery": "gallery_page",
  "/gallery/pools": "gallerypools_page",
  "/gallery/patios": "gallerypatios_page",
  "/gallery/sidewalks": "gallerysidewalks_page",
  "/gallery/porches-steps": "galleryporchessteps_page",
  "/gallery/driveways": "gallerydriveways_page",
  "/gallery/pavers": "gallerypavers_page",
  "/gallery/commercial": "gallerycommercial_page",
  "/gallery/garage-floor-barn": "gallerygaragebarn_page",
  "/gallery/sport-court": "gallerysportcourt_page",
  "/finishes": "finishes_page",
  "/finishes/broom": "finishesbroom_page",
  "/finishes/colored-broom": "finishescoloredbroom_page",
  "/finishes/stamped-colored": "finishesstampedcolored_page",
  "/finishes/smooth": "finishessmooth_page",
  "/finishes/buff-wash-exposed": "finishesbuffwash_page",
  "/commercial": "commercial_page",
  "/commercial-concrete": "commercialconcrete_page",
  "/commercial-pools": "commercialpools_page",
  "/why-maxima": "whymaxima_page",
  "/join-our-team": "joinourteam_page",
  "/contact-us": "contactus_page",
  "/project-map": "projectmap_page",
  "/areas-we-serve": "areaswe_serve_page",
  "/areas-we-serve/columbus": "areascolumbus_page",
};

// Páginas sem JSON de seções (conteúdo próprio no código)
export const STATIC_ROUTES = ["/reviews", "/financing", "/licensing-insured"];
